version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mascotin-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ao49fmsk
      MYSQL_DATABASE: miaplicaciondb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pao49fmsk"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 90s
    networks:
      - mascotin-net

  app:
    build: .
    container_name: mascotin-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - mascotin-net

networks:
  mascotin-net:
    driver: bridge